### ISSUE TITLE
Commit.committer.date is str, not datetime

### ISSUE THREAD

**Issue by brandonchinn178** [yanyongyu/githubkit#199]
If you look at the OpenAPI spec, the get-commit endpoint returns a commit object containing committer with a date field, which is a string with date-time format. But githubkit's endpoint returns a Commit object containing GitUser where date is just a str, so the user needs to parse the datetime themselves

**Comment by yanyongyu** [comment]
Do you mean the `/components/schemas/commit/properties/commit/properties/committer`？Its type is `git-user`:

```yaml
git-user:
  title: Git User
  description: Metaproperties for Git author/committer information.
  type: object
  properties:
    name:
      type: string
      examples:
      - '"Chris Wanstrath"'
    email:
      type: string
      examples:
      - '"chris@ozmm.org"'
    date:
      type: string
      examples:
      - '"2007-10-29T02:42:39.000-07:00"'
```

As the schema shows, the `date` field is string but not date. If you think this should be date type, you can report this to https://github.com/github/rest-api-description/ and i will make a patch to add a `format: date-time` to this field.
