### ISSUE TITLE
Bug: `repos/get-content` response model uncorrect

### ISSUE THREAD

**Issue by yanyongyu** [yanyongyu/githubkit#3]
```yaml
schema:
  oneOf:
    - "$ref": "#/components/schemas/content-directory"
    - "$ref": "#/components/schemas/content-file"
    - "$ref": "#/components/schemas/content-symlink"
    - "$ref": "#/components/schemas/content-submodule"
```
